"""initial schema

Revision ID: 75e1a8df16c6
Revises: 
Create Date: 2026-09-15 19:36:31.878982

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '75e1a8df16c6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('pieces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seller_user_id', sa.Integer(), nullable=True),
    sa.Column('pseudonym', sa.String(length=120), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('micro', sa.String(length=280), nullable=False),
    sa.Column('textile', sa.String(length=200), nullable=False),
    sa.Column('dims', sa.String(length=120), nullable=False),
    sa.Column('story', sa.Text(), nullable=False),
    sa.Column('care', sa.Text(), nullable=False),
    sa.Column('price_cents', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['seller_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('piece_id', sa.Integer(), nullable=False),
    sa.Column('buyer_name', sa.String(length=200), nullable=False),
    sa.Column('buyer_email', sa.String(length=320), nullable=False),
    sa.Column('buyer_phone', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('method', sa.String(length=32), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('reference_code', sa.String(length=16), nullable=False),
    sa.Column('provider_ref', sa.String(length=255), nullable=True),
    sa.Column('handover_area', sa.String(length=120), nullable=True),
    sa.Column('handover_window', sa.String(length=200), nullable=True),
    sa.Column('handover_place_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['piece_id'], ['pieces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_piece_id'), 'orders', ['piece_id'], unique=False)
    op.create_index(op.f('ix_orders_reference_code'), 'orders', ['reference_code'], unique=True)
    op.create_table('piece_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('piece_id', sa.Integer(), nullable=False),
    sa.Column('slot', sa.Integer(), nullable=False),
    sa.Column('original_path', sa.String(length=512), nullable=False),
    sa.Column('cutout_path', sa.String(length=512), nullable=False),
    sa.Column('plate_path', sa.String(length=512), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('dominant_palette', sa.JSON(), nullable=True),
    sa.Column('bg_state', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['piece_id'], ['pieces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_piece_images_piece_id'), 'piece_images', ['piece_id'], unique=False)
    op.create_table('payment_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('provider_event_id', sa.String(length=255), nullable=False),
    sa.Column('event_type', sa.String(length=128), nullable=False),
    sa.Column('signature_valid', sa.Boolean(), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_event_id', name='uq_provider_event')
    )
    op.create_index(op.f('ix_payment_events_order_id'), 'payment_events', ['order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payment_events_order_id'), table_name='payment_events')
    op.drop_table('payment_events')
    op.drop_index(op.f('ix_piece_images_piece_id'), table_name='piece_images')
    op.drop_table('piece_images')
    op.drop_index(op.f('ix_orders_reference_code'), table_name='orders')
    op.drop_index(op.f('ix_orders_piece_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_table('pieces')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
